title: Status
url: "https://status.omgmog.net"

collections:
  updates:
    output: true
    permalink: /:title/

defaults:
  - scope:
      path: ""
      type: updates
    values:
      layout: update
