title: Status
url: "https://status.omgmog.net"
author:
  github: omgmog
  twitter: omgmog
  name: Max Glenister
exclude: ["newpost"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  updates:
    output: true
    permalink: /:title/

defaults:
  - scope:
      path: ""
      type: updates
    values:
      layout: update
